name = "chrona"
main = "worker.js"
compatibility_date = "2024-11-01"

# [[kv_namespaces]]
# binding = "VERIFICATION_KV"
# id = "your-kv-id"   # استبدل بالمعرف الفعلي

[vars]
GITHUB_OWNER = "bergham123"
GITHUB_REPO = "chrona"
GITHUB_BRANCH = "main"
ADMIN_USERNAME = "mohammed"   # المستخدم الذي سيكون مشرفاً
